var albums=[
  { type: "album",
  albumTitle: "Asheville",
  albumCover:"images/asheville10.jpg",
    asheville: [
      {photoName:"Asheville1",
      photoUrl:"images/asheville10.jpg",},
      {photoName:"Asheville2",
      photoUrl:"images/asheville2.jpg",},
      {photoName:"Asheville3",
      photoUrl:"images/asheville9.jpg",},
      {photoName:"Asheville4",
      photoName:"images/asheville4.jpg",},
      {photoName:"Asheville5",
      photoUrl:"images/asheville5.jpg",},
      {photoName:"Asheville6",
      photoUrl:"images/asheville8.jpg",},
    ],
  },

    { type: "album",
    albumTitle: "Costumes",
    albumCover:"images/costume1.jpg",
    costumes: [
      {photoName:"Costume1",
      photoUrl: "images/costume1.jpg",},
      {photoName:"Costume2",
      photoUrl: "images/costume5.jpg",},
      {photoName:"Costume3",
      photoUrl:"images/costume1.jpg",},
      {photoName:"Costume4",
      photoUrl:"images/costume1.jpg",},
      {photoName:"Costume5",
      photoUrl:"images/costume1.jpg",},
      {photoName:"Costume6",
      photoUrl:"images/costume1.jpg",},
    ],
  },
    { type: "album",
    albumTitle: "Crafts",
    albumCover:"images/craft2.jpg",
    crafts: [
      {photoName:"Craft1",
      photoUrl:"images/craft2.jpg",},
      {photoName:"Craft2",
      photoUrl:"images/craft1.jpg",},
      {photoName:"Craft3",
      photoUrl:"images/craft12.jpg",},
      {photoName:"Craft4",
      photoUrl:"images/craft7.jpg",},
      {photoName:"Craft5",
      photoUrl:"images/craft3.jpg",},
      {photoName:"Craft6",
      photoUrl:"images/craft8.jpg",},
    ],
  },

  { type: "album",
    albumTitle: "Dance",
    albumCover:"images/dance8.jpg",
    dance: [
      {photoName:"Dance1",
      photoUrl:"images/dance8.jpg",},
      {photoName:"Dance2",
      photoUrl:"images/dance1.jpg",},
      {photoName:"Dance3",
      photoUrl:"images/dance2.jpg",},
      {photoName:"Dance4",
      photoUrl:"images/dance3.jpg",},
      {photoName:"Dance5",
      photoUrl:"images/dance6.jpg",},
      {photoName:"Dance6",
      photoUrl:"images/dance11.jpg",},
    ],
  },
  { type: "album",
    albumTitle: "Family",
    albumCover:"images/family1.jpg",
    family: [
      {photoName:"Family1",
      photoUrl:"images/family1.jpg",},
      {photoName:"Family2",
      photoUrl:"images/family2.jpg",},
      {photoName:"Family3",
      photoUrl:"images/family3.jpg",},
      {photoName:"Family4",
      photoUrl:"images/family4.jpg",},
      {photoName:"Family5",
      photoUrl:"images/family6.jpg",},
      {photoName:"Family6",
      photoUrl:"images/family5.jpg",},
    ],
  },
  {type: "album",
    albumTitle: "Music",
    albumCover:"images/music5.jpg",
    music:[
      {photoName:"Music1",
      photoUrl:"images/music5.jpg",},
      {photoName:"Music2",
      photoUrl:"images/music1.jpg",},
      {photoName:"Music3",
      photoUrl:"images/music3.jpg",},
      {photoName:"Music4",
      photoUrl:"images/music4.jpg",},
      {photoName:"Music5",
      photoUrl:"images/music8.jpg",},
      {photoName:"Music6",
      photoUrl:"images/music2.jpg",},
    ],
  },
];
